/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as QuienesSomosRouteImport } from './routes/quienes-somos'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as EmergenciasRouteImport } from './routes/emergencias'
import { Route as CuentaRouteImport } from './routes/cuenta'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReservarIdRouteImport } from './routes/reservar.$id'
import { Route as PropertyIdRouteImport } from './routes/property.$id'

const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const QuienesSomosRoute = QuienesSomosRouteImport.update({
  id: '/quienes-somos',
  path: '/quienes-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergenciasRoute = EmergenciasRouteImport.update({
  id: '/emergencias',
  path: '/emergencias',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaRoute = CuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservarIdRoute = ReservarIdRouteImport.update({
  id: '/reservar/$id',
  path: '/reservar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cuenta': typeof CuentaRoute
  '/emergencias': typeof EmergenciasRoute
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/privacidad': typeof PrivacidadRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/terminos': typeof TerminosRoute
  '/property/$id': typeof PropertyIdRoute
  '/reservar/$id': typeof ReservarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cuenta': typeof CuentaRoute
  '/emergencias': typeof EmergenciasRoute
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/privacidad': typeof PrivacidadRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/terminos': typeof TerminosRoute
  '/property/$id': typeof PropertyIdRoute
  '/reservar/$id': typeof ReservarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cuenta': typeof CuentaRoute
  '/emergencias': typeof EmergenciasRoute
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/privacidad': typeof PrivacidadRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/terminos': typeof TerminosRoute
  '/property/$id': typeof PropertyIdRoute
  '/reservar/$id': typeof ReservarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cuenta'
    | '/emergencias'
    | '/explorar'
    | '/login'
    | '/privacidad'
    | '/quienes-somos'
    | '/terminos'
    | '/property/$id'
    | '/reservar/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cuenta'
    | '/emergencias'
    | '/explorar'
    | '/login'
    | '/privacidad'
    | '/quienes-somos'
    | '/terminos'
    | '/property/$id'
    | '/reservar/$id'
  id:
    | '__root__'
    | '/'
    | '/cuenta'
    | '/emergencias'
    | '/explorar'
    | '/login'
    | '/privacidad'
    | '/quienes-somos'
    | '/terminos'
    | '/property/$id'
    | '/reservar/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CuentaRoute: typeof CuentaRoute
  EmergenciasRoute: typeof EmergenciasRoute
  ExplorarRoute: typeof ExplorarRoute
  LoginRoute: typeof LoginRoute
  PrivacidadRoute: typeof PrivacidadRoute
  QuienesSomosRoute: typeof QuienesSomosRoute
  TerminosRoute: typeof TerminosRoute
  PropertyIdRoute: typeof PropertyIdRoute
  ReservarIdRoute: typeof ReservarIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quienes-somos': {
      id: '/quienes-somos'
      path: '/quienes-somos'
      fullPath: '/quienes-somos'
      preLoaderRoute: typeof QuienesSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergencias': {
      id: '/emergencias'
      path: '/emergencias'
      fullPath: '/emergencias'
      preLoaderRoute: typeof EmergenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta': {
      id: '/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof CuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservar/$id': {
      id: '/reservar/$id'
      path: '/reservar/$id'
      fullPath: '/reservar/$id'
      preLoaderRoute: typeof ReservarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$id': {
      id: '/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof PropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CuentaRoute: CuentaRoute,
  EmergenciasRoute: EmergenciasRoute,
  ExplorarRoute: ExplorarRoute,
  LoginRoute: LoginRoute,
  PrivacidadRoute: PrivacidadRoute,
  QuienesSomosRoute: QuienesSomosRoute,
  TerminosRoute: TerminosRoute,
  PropertyIdRoute: PropertyIdRoute,
  ReservarIdRoute: ReservarIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
